<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>generator</title>
  <script>
    console.log('---------1----------')
    // 类似普通函数写法
    // 1. *
    // 2. yield
    function* helloWorldGenerator() {
      yield 'hello';
      yield 'world';
      return 'ending';
    }
    // 返回的是遍历器对象
    var hw = helloWorldGenerator();
    // 遍历器对象的next方法
    console.log(hw.next()) // {value: "hello", done: false}
    console.log(hw.next()) // {value: "world", done: false}
    console.log(hw.next()) // {value: "ending", done: true}
    console.log(hw.next()) // {value: undefined, done: true}

    console.log('----------2---------')
    function* demo() {
      // console.log('Hello' + (yield)); // OK
      console.log('Hello' + (yield 123)); // OK
    }
    var demo = demo()
    console.log(demo.next())
    console.log(demo.next())

    console.log('-----------3--------')
    function* f() {
      for(var i = 0; true; i++) {
        var reset = yield i;
        if(reset) { i = -1; }
      }
    }
    var g = f();
    console.log(g.next()) // { value: 0, done: false }
    console.log(g.next()) // { value: 1, done: false }
    // next方法可以带一个参数，该参数就会被当作上一个yield表达式的返回值。
    console.log(g.next(true)) // { value: 0, done: false }

    console.log('-----------4--------')
    function* foo(x) {
      var y = 2 * (yield (x + 1));
      var z = yield (y / 3);
      return (x + y + z);
    }

    var a = foo(5);
    console.log(a.next()) // Object{value:6, done:false}
    console.log(a.next()) // Object{value:NaN, done:false}
    console.log(a.next()) // Object{value:NaN, done:true}
    // next方法的参数表示上一个yield表达式的返回值
    var b = foo(5);
    // 第一次使用next方法时，传递参数是无效的
    console.log(b.next()) // { value:6, done:false }
    console.log(b.next(12)) // { value:8, done:false }
    console.log(b.next(13)) // { value:42, done:true }

    console.log('-----------5--------')
    function* dataConsumer() {
      console.log('Started');
      console.log(`1. ${yield}`);
      console.log(`2. ${yield}`);
      return 'result';
    }

    let genObj = dataConsumer();
    genObj.next();
    // Started
    genObj.next('a')
    // 1. a
    genObj.next('b')
    // 2. b
    console.log('-----------6--------')
    function* foo() {
      yield 1;
      yield 2;
      yield 3;
      yield 4;
      yield 5;
      return 6;
    }

    // for...of循环可以自动遍历 Generator 函数运行时生成的Iterator对象，且此时不再需要调用next方法。
    for (let v of foo()) {
      console.log(v);
    }
    // 1 2 3 4 5
    // 返回对象的done属性为true，for of 就终止，return 不在循环中

    console.log('-----------7--------')
    function* fibonacci() {
      let [prev, curr] = [0, 1];
      for (;;) {
        yield curr;
        [prev, curr] = [curr, prev + curr];
      }
    }
    for (let n of fibonacci()) {
      if (n > 1000) break;
      console.log(n);
    }

    console.log('-----------8 Generator.prototype.throw() --------')
    var g = function* () {
      try {
        yield;
      } catch (e) {
        console.log('内部捕获', e);
      }
    };
    var i = g();
    i.next();
    try {
      i.throw('a');
      i.throw('b');
    } catch (e) {
      console.log('外部捕获', e);
    }

    console.log('-----------9--------')
    var g2 = function* () {
      while (true) {
        try {
          yield;
        } catch (e) {
          if (e != 'a') throw e;
          console.log('内部捕获', e);
        }
      }
    };

    var i = g2();
    i.next();

    try {
      throw new Error('a');
      throw new Error('b');
    } catch (e) {
      console.log('外部捕获', e);
    }
    // 外部捕获 [Error: a]

    console.log('-----------10--------')
    function* gen() {
      try {
        yield 1;
      } catch (e) {
        console.log('内部捕获');
      }
    }

    var g = gen();
    // throw方法抛出的错误要被内部捕获，前提是必须至少执行过一次next方法。
    g.next()
    g.throw(1);

    console.log('-----------11--------')
    var gen2 = function* gen2(){
      try {
        yield console.log('a');
      } catch (e) {
        // ...
      }
      yield console.log('b');
      yield console.log('c');
    }

    var g = gen2();
    g.next() // a
    // g.throw方法被捕获以后，自动执行了一次next方法
    g.throw() // b
    g.next() // c

    console.log('-----------12--------')
    // 一旦 Generator 执行过程中抛出错误，且没有被内部捕获，就不会再执行下去了。如果此后还调用next方法，将返回一个value属性等于undefined、done属性
    function* g() {
      yield 1;
      console.log('throwing an exception');
      throw new Error('generator broke!');
      yield 2;
      yield 3;
    }

    function log(generator) {
      var v;
      console.log('starting generator');
      try {
        v = generator.next();
        console.log('第一次运行next方法', v);
      } catch (err) {
        console.log('捕捉错误', v);
      }
      try {
        v = generator.next();
        console.log('第二次运行next方法', v);
      } catch (err) {
        console.log('捕捉错误', v);
      }
      try {
        v = generator.next();
        console.log('第三次运行next方法', v);
      } catch (err) {
        console.log('捕捉错误', v);
      }
      console.log('caller done');
    }

    // log(g());
    // starting generator
    // 第一次运行next方法 { value: 1, done: false }
    // throwing an exception
    // 捕捉错误 { value: 1, done: false }
    // 第三次运行next方法 { value: undefined, done: true }
    // caller done

    console.log('-----------13 Generator.prototype.return--------')
    function* gen3() {
      yield 1;
      yield 2;
      yield 3;
    }

    var g = gen3();

    g.next()        // { value: 1, done: false }
    // 返回给定的值，并且终结遍历 Generator 函数。
    g.return('foo') // { value: "foo", done: true }
    g.next()        // { value: undefined, done: true }

    console.log('-----------14--------')
    // Generator 函数内部有try...finally代码块，且正在执行try代码块，那么return方法会推迟到finally代码块执行完再执行
    function* numbers () {
      yield 1;
      try {
        yield 2;
        yield 3;
      } finally {
        yield 4;
        yield 5;
      }
      yield 6;
    }
    var g = numbers();
    g.next() // { value: 1, done: false }
    g.next() // { value: 2, done: false }
    g.return(7) // { value: 4, done: false }
    g.next() // { value: 5, done: false }
    g.next() // { value: 7, done: true }

    console.log('-----------15--------')
    function* inner() {
      yield 'hello!';
    }

    function* outer1() {
      yield 'open';
      yield inner();
      yield 'close';
    }

    var gen = outer1()
    gen.next().value // "open"
    gen.next().value // 返回一个遍历器对象
    gen.next().value // "close"

    function* outer2() {
      yield 'open'
      yield* inner()
      yield 'close'
    }

    var gen = outer2()
    gen.next().value // "open"
    gen.next().value // "hello!"
    gen.next().value // "close"

    console.log('-----------16--------')
    const tree = [ 'a', ['b', 'c'], ['d', 'e'] ];
    function* iterArr(tree){
      if(Array.isArray(tree)){
        for(var i=0;i<tree.length;i++){
          yield* iterArr(tree[i])
        }
      }else{
        yield tree
      }
    }
    // console.log(iterArr(tree))
    for(var v of iterArr(tree)){
      console.log(v)
    }
    console.log('-----------17--------')
    function* main() {
      var result = yield request("data.json");
      var resp = JSON.parse(result);
      console.log(resp.value);
    }

    function request(url) {
      var xmlHttp;
      if(window.XMLHttpRequest){
        xmlHttp = new XMLHttpRequest()
      }
      xmlHttp.open('get', url)
      xmlHttp.onreadystatechange = function(){
        if(xmlHttp.readyState==4&&xmlHttp.status==200){
          console.log(JSON.parse(xmlHttp.responseText).value)
          it.next(xmlHttp.responseText)
        }
      }
      xmlHttp.send()
      // $.ajax({
      //   url:url,
      //   dataType:'json',
      //   success:function(){
      //     it.next(response);
      //   }
      // })
      // makeAjaxCall(url, function(response){
      //   it.next(response);
      // });
    }

    var it = main();
    it.next();
    
  </script>
</head>
<body>
  <div>

  </div>
</body>
</html>